# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='ready',
            field=models.BooleanField(default=False, help_text='Click if push are ready to be sent.', verbose_name='Ready to Send?'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='date',
            field=models.DateTimeField(help_text='Date that this push notification must be sent', verbose_name='Push Date'),
        ),
    ]
