# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0002_auto_20170405_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=20, verbose_name='Display Name')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CoReceivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push.CoReceiver')),
            ],
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='co_receivers_only',
            field=models.BooleanField(default=True, help_text='Check if you want to send only for test users.', verbose_name='Only co-receivers?'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='co_receivers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='push.CoReceivers'),
        ),
    ]
