# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0003_auto_20170405_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreceivers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='co_receivers',
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='co_receivers',
            field=models.ManyToManyField(null=True, to='push.CoReceiver'),
        ),
        migrations.DeleteModel(
            name='CoReceivers',
        ),
    ]
