# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0009_country_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='filters',
            field=models.ManyToManyField(to='push.Filter'),
        ),
    ]
