# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0010_pushnotification_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='filters',
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='push.Filter'),
        ),
    ]
