# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0011_auto_20170405_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushnotification',
            old_name='filter',
            new_name='filters',
        ),
    ]
