# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0012_auto_20170405_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='filters',
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='countries',
            field=models.ManyToManyField(to='push.Country'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name='Last Login'),
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
