# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0014_polygon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polygon',
            old_name='polygon',
            new_name='geom',
        ),
    ]
