# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0015_auto_20170406_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='matches',
            field=models.CharField(default='en', help_text='Comma-separated values of languages to match', max_length=20),
            preserve_default=False,
        ),
    ]
