# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0016_language_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.IntegerField()),
                ('fail', models.IntegerField()),
                ('push', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push.PushNotification')),
            ],
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='polygon',
            name='geom',
            field=djgeojson.fields.GeoJSONField(verbose_name='Geometry'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='message_config',
            field=models.ForeignKey(default=1, help_text="Defines message's title and icon", on_delete=django.db.models.deletion.CASCADE, to='push.MessageConfig'),
            preserve_default=False,
        ),
    ]
