# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0017_auto_20170408_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreceiver',
            name='display_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='deeplink',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='iso_code',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
